language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate && metricly package lint
notifications:
  slack:
    secure: lp03WpnPFkcgfk9T+d8nOhixVhAukoIhrTGKodTbRR7R/TfRsNvtpE6646ShH+t0YNB5V4HA9iZBBHnL5VvletIuCogRspLPrZVv9Odl+p459sGpRAy7fIxNMZcLNGwBvpJcdtJBtC7UrWgS5FKPSBX1aKh/2uf9VmW2r+rXe04Pblmb/0KNJLQih1k5p5AIqJxpkcD/YAhv/kAOaMAXL8+ed6SRqScz1LSzOCwxdwUPRYN6yzHD/gHgs3ypSXeFv2bo49r8OolfwVRHmOH+7+ls9DFNR51hoBDn1/EqS3iC2mBzJ/Bwk3t29flEXVbePfX2achmw0CUlx7EjX4eyoYEnZsJR6pgdT6XQt0olagYbHpT6wqlKXNsk9uBpm3/TPsw2FRRQSAWoq7syvhDxKtGahK9yaYzOWe0d2np4c5d5c6wU67/riadkIDn4NHDGX0TBMjbuNyepZZvQvFmtCCD9eXx6tDpCgsuS0Qjt2Rc84YC0tRoCUYpeXzvPKA8QnGzJzTIAxOfav0iVsPqqMI+u1XR+7pslITcw2Pj/qbNXOcaw6OHmAgTtFhViXK+paZD6c+vcUmP3QJTVecv925qTGTphkJWWjDCdyNaoXXSnDptkLIA9MMJ3KYzE9Xi4Eh30QUyhpBt/omDnYz6UPeNDbP4MQpGbb27uLsNa2c=
