language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate && metricly package lint
notifications:
  slack:
    secure: f2qx/yp11S3s4de+ayk4ODo0vd896n2deWhpietsLKDms9XxiqoT8aYh0K/Ags67nZOG4awdFh4G6L5owdXPIgSo7b9Q0knmLxvCnoVNnNn3NZj6q1UBGb5Jp/xRtikqQyJ0q4wthwTL8/p06K6VuSL3JiIksKeWNSLQ6Meuc15NR2Qbl4INLYEMNTZCyN7fxSaRCVXDrA6Asou2aZVKusgdX6Ln3qhlvk0qTa9Lqm6yDFmXlK6Jj1JUEBESFLYAnUwwZhtrJsn3pLIzwu3+kYa48EusyY1Wr9bp6wkHIYMKQEXDJUOICeeQcR2kU4wPhK+Wx+yWvGELHEMHMXbuQssWGFMjQaUGRYNeJMaYmO1+DwFjwCMiAKRA7HAdU66klamm8ZTRlJlx6rVbSoxhcrdz/VWyPTfaceXxjTefwsJFBWsm6REabkt6Wj22YD9xuZwtAWfG3P/cLlaFZZ6t+kVp9C1iqpBJNxxlG13xSMLlsy5jUWwY3TTLU9D/wIvFhfo486wZ7Zl59/4Qmfe31uNiRIC/XLjE11gL1XEhsADF94zPCnjWl0xmhw7cTv2/t2SUGSHVzBTWc13SD8CgEn/fbxEZex0ZH94FCUho1q+WFDsYtURILgDGaSAa0go0+ZOOsK462LCQeQkDxuDuKzDbHR5AJzqoqmGG6d9xQtI=
